[package]
name = "bilitools"
version = "1.0.3"
description = "BiliTools"
authors = ["btjawa"]
license = "MIT"
repository = "git+https://github.com/btjawa/BiliTools.git"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
log4rs = "1.0"
log = "0.4"
chrono = "0.4"
rusqlite = { version = "0.27.0", features = ["bundled"] }
regex = "1.10.2"
futures = "0.3"
tauri = { version = "1.5.4", features = [ "clipboard-all", "dialog-save", "shell-open", "updater", "os-all", "dialog-open", "http-request"] }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11.9", features = ["json", "cookies", "stream", "deflate", "gzip", "brotli"] }
warp = "0.3.6"
lazy_static = "1.4.0"
tokio = { version = "1", features = ["full"] }
rand = "0.8.5"
walkdir = "2.4.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
