[package]
name = "bilitools"
version = "1.3.0-dev.4"
description = "BiliTools - 哔哩哔哩工具箱"
authors = ["btjawa"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "z" # Optimize for binary size
strip = true # Remove debug symbols

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }

[dependencies]
tauri = { version = "2.1.1", features = ["macos-private-api"] }
tauri-plugin-single-instance = "2.0.1"
tauri-plugin-shell = "2.0.2"
tauri-plugin-dialog = "2.0.3"
tauri-plugin-log = "2.0.2"
tauri-plugin-os = "2.0.1"
tauri-plugin-fs = "2.0.3"
tauri-plugin-process = "2.0.1"
tauri-plugin-http = { version = "2.0.3", features = ["unsafe-headers", "rustls-tls", "stream", "gzip", "brotli", "blocking"] }
sea-orm = { version = "0.12", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1.11.1"
log = "0.4"
lazy_static = "1.5.0"
tokio = { version = "1.41", features = ["macros", "io-util", "sync", "time", "fs", "signal"] }
rand = "0.8.5"
walkdir = "2.5.0"
window-vibrancy = "0.5.2"
ring = "0.17.8"
win32job = "2.0.0"
sys-locale = "0.3.2"

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-updater = "2.0.2"
