[package]
name = "bilitools"
version = "1.1.2"
description = "BiliTools - bilibili工具箱"
authors = ["btjawa"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "z" # Optimize for binary size
strip = true # Remove debug symbols

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = ["macos-private-api"] }
tauri-plugin-single-instance = "2.0.0-beta"
tauri-plugin-shell = "2.0.0-beta"
tauri-plugin-dialog = "2.0.0-beta"
tauri-plugin-os = "2.0.0-beta"
tauri-plugin-store = "2.0.0-beta"
tauri-plugin-http = { version = "2.0.0-beta", features = ["unsafe-headers", "rustls-tls", "stream", "gzip", "brotli"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1.10.2"
log4rs = "1.0"
log = "0.4"
lazy_static = "1.4.0"
tokio = { version = "1.0", features = ["macros", "io-util", "sync", "time", "fs", "signal"] }
rand = "0.8.5"
walkdir = "2.4.0"
window-vibrancy = "0.5.0"
chrono = "0.4.37"
dirs-next = "2.0"

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-updater = "2.0.0-beta.3"

[target."cfg(target_os = \"windows\")".dependencies]
win32job = "2.0.0"

[target."cfg(target_os = \"macos\")".dependencies]
nix = "0.23"
