name: Bug report / 反馈 Bug
description: Bug report / 反馈 Bug
title: "[Bug] "
labels: ["bug", "needs triage"]
assignees: []

body:
  - type: checkboxes
    attributes:
      label: Please confirm before submitting
      options:
        - label: |
            I'm sure there are no duplicate issues or discussions.
            我确定没有重复的 Issue 或 Discussion。
          required: true
        - label: |
            I'm sure it's BiliTools' problem and not something else.
            我确定这是 BiliTools 的问题，而不是其他个人因素、网络因素等原因。
          required: true
        - label: |
            I have read the [Contributing](https://github.com/btjawa/BiliTools/blob/master/CONTRIBUTING.md).
            我已阅读 [Contributing](https://github.com/btjawa/BiliTools/blob/master/CONTRIBUTING.md)。
          required: true
  - type: textarea
    attributes:
      label: BiliTools version / BiliTools 版本
      description: |
        Please use the exact version code.
        请使用确切的版本号。
      placeholder: v1.x.x
    validations:
      required: true
  - type: textarea
    attributes:
      label: Download link / 下载的资源链接
      description: |
        This can be a URL, or AV / BV number, etc.
        可以是 URL 链接，或是 AV / BV 号等。

  - type: textarea
    attributes:
      label: Describe the bug / 问题描述
    validations:
      required: true

  - type: dropdown
    attributes:
      label: System type / 系统类型
      options:
        - Windows 10
        - Windows 11
        - macOS M-series Chip
        - macOS Intel Chip
        - Linux (Please add your distribution in Reproduction)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction / 复现步骤
      description: |
        How to reproduce the problem you ran into?
        如何复现你提到的问题？
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs / 日志
      description: |
        Please upload your logs.
        请上传你的日志文件。

        Windows: %LOCALAPPDATA%\com.btjawa.bilitools\logs
        macOS: $HOME/Library/Logs/com.btjawa.bilitools
    validations:
      required: true