name: Feature Request / 功能请求
description: Feature Request / 功能请求
title: "[Feature Request] "
labels: ["enhancement", "needs triage"]
assignees: []

body:
  - type: checkboxes
    attributes:
      label: Please confirm before submitting
      options:
        - label: |
            I have read the [Contributing](https://github.com/btjawa/BiliTools/blob/master/CONTRIBUTING.md).
            我已阅读 [Contributing](https://github.com/btjawa/BiliTools/blob/master/CONTRIBUTING.md)。
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description / 功能简述
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: Implement Reference / 实现参考
    validations:
      required: true