name: 功能请求
description: 需要什么新功能？
title: "[功能请求] "
labels: ["enhancement", "needs triage"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: 功能简述
      description: 请对新功能进行详细描述
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: 实现参考
      description: 已有实现思路或参考？
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: 系统环境
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true