name: 'release'

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows x86_64
          - platform: 'windows-2025'
            target: 'x86_64-pc-windows-msvc'
            args: '--target x86_64-pc-windows-msvc'
          # Windows arm64
          # - platform: 'windows-11-arm'
          #   target: 'aarch64-pc-windows-msvc'
          #   args: '--target aarch64-pc-windows-msvc'
          # Linux x86_64
          - platform: 'ubuntu-22.04'
            target: 'x86_64-unknown-linux-gnu'
            args: --target x86_64-unknown-linux-gnu --config ./src-tauri/tauri.linux.conf.json --config ./src-tauri/tauri.linux.amd64.conf.json
          # Linux arm64
          - platform: 'ubuntu-22.04-arm'
            target: 'aarch64-unknown-linux-gnu'
            args: --target aarch64-unknown-linux-gnu --config ./src-tauri/tauri.linux.conf.json --config ./src-tauri/tauri.linux.arm64.conf.json
          # macOS x86_64 (Intel)
          - platform: 'macos-14'
            target: 'x86_64-apple-darwin'
            args: --target x86_64-apple-darwin
          # macOS arm64 (M1 and above)
          - platform: 'macos-14'
            target: 'aarch64-apple-darwin'
            args: --target aarch64-apple-darwin

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          save-if: false

      - name: Install Dependencies (ubuntu only)
        if: startsWith(matrix.platform, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf rpm xdg-utils desktop-file-utils
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.

      - name: Install Frontend Dependencies
        run: pnpm install --frozen-lockfile

      - name: Get UpdateLog
        id: updatelog
        run: pnpm ci:updatelog ${{ github.ref_name }}

      - name: Tauri Build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'BiliTools | ${{ github.ref_name }}'
          releaseBody: ${{ steps.updatelog.outputs.body }}
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true
          args: ${{ matrix.args }}
